version: "3.8"
services:
  postgresql-db:
    image: "postgres:latest"
    container_name: flag-db
    ports:
      - 5432:5432
    networks:
      - db_net
    environment:
      - DEBUG=false
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  db_net:

volumes:
  db_data:
